### ISSUE TITLE
[PRODUCT FEEDBACK] 

### ISSUE THREAD

**Issue by Yusadem131** [microsoft/30daysof#102]
## Submitted By
(Yusadem131 - preferably GitHub profile name)

## Your Role
> What is your role in this learning context?
> - Student
---

## For Product
> What do you have feedback on?
> - Submitting Quickbooks Proposal
> - A Technology Topic
Specify a name and _share a link to the learning resource you were using_ 

---

## Description
(1-2 lines that describe the topic or focus of your feedback)
* `Example 1: Bug Report`: Error using feature _git fetch upstream_ on product git_. 
* `Example 2: Feature Request`: Request to add feature _xxx_ to product _yyy_

---

## Details
(Use this section to provide more details on the feedback if possible)
* `Example 1: Bug report`: 
  - When I tried doing `git fetch upstream`
  - I got this error message: `remote: Repository not found.
fatal: repository 'https://github.com/microsoft/PowerPlatformConectors/' not found
`
  - To reproduce the error, take these steps: `describe steps you took`
  - (Optional) Take and share a screenshot if possible
* `Example 2: Feature request`: 
  - I want to `use case you are implementing`
  - But this product does not currently have `feature you want`
  - Adding this feature will have these benefits: `describe how it improves developer experience`

---

**Comment by juliamuiruri4** [comment]
Hi @Yusadem131 - Would you mind sharing screenshots or a screen record of how you are arriving to this error please?

Also, in case you were able to solve it, please let us know to update the issue accordingly. Regards

**Comment by juliamuiruri4** [comment]
Reference materials
[Full Git documentation](https://git-scm.com/docs)  
[Git fetch documentation](https://git-scm.com/docs/git-fetch)

Please let me know if you get answers here.

**Comment by Yusadem131** [comment]
I have submitted the pull request.

**Comment by Yusadem131** [comment]
I have closed it. Thanks @juliamuiruri4

**Comment by japhletnwamu** [comment]
Thanks for submitting your pull requests. I'm glad this has worked out for
you.

Enjoy the remaining part of the hackathon and I can't wait to see what
amazing solutions you come up with.

Regards!

**Comment by Yusadem131** [comment]
I haven't been able to create the connector and finish it. I need help on this. Thanks @japhletnwamu
