### ISSUE TITLE
[Microsoft Graph Project Submission]

### ISSUE THREAD

**Issue by Avishasa** [microsoft/30daysof#154]
## Submitted By
> Avishag Saban 

### github explorer
I need help using sandbox environment. 
On the graph explorer, I'm connected with my company's email. And the tenant that's provided is my company's real data.
I've created a sandbox environment, but how to change to the sandbox option?

Thanks

**Comment by aycabas** [comment]
Hi @Avishasa, you can sign out from Graph Explorer and sign in with your sandbox account: 
![image](https://user-images.githubusercontent.com/36196437/204233512-96057c04-54cc-497b-b92b-0c00c24251d6.png)

If you have any issues or questions, feel free to ask in the GitHub discussions: https://aka.ms/30DaysOfMSGraph/GitHub
