### ISSUE TITLE
A11y_30days_Welcome to 30 Days of Learning_Usability: While Pressing the “Esc” key “Submenu” is not getting collapse.

### ISSUE THREAD

**Issue by Ashutoshsahoo164** [microsoft/30daysof#170]
"[Check out Accessibility Insights](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0)! - Identify accessibility bugs before check-in and make bug fixing faster and easier."

### GitHub Tags:

#A11yTCS; #A11ySev4;#A11yUsable;#30days;#P3_30days_Dec22;#DesktopWeb;#Win11;ChromiumEdge

### Environment Details:
Application Name: 30days 
#URL: https://microsoft.github.io/30daysof/
Windows Version: Win11
Chromium Edge Version: 110.0.1556.0 (Official build) dev (64-bit)
### Repro Steps:
1.	Hit the URL: https://microsoft.github.io/30daysof/ 
2.	Home page will open then tab to "Self Paced" present in header section and press Enter.
3.	Self paced submenu will open. Press the “Esc” key
4.	Observe while pressing the “Esc” key submenu is not getting collapsed.
### Actual:
While pressing the “Esc” key submenu is not getting collapsed.
Note – This issue is observed throughout the application.
### Expected:
While pressing the “Esc” key submenu should get collapse
### User Impact:
Keyboard only users will not be able to collapse the submenu.

### Attachment

https://user-images.githubusercontent.com/85863895/211752472-18435a86-bf07-4805-b6be-d40b14dc59ea.mp4

**Comment by nitya** [comment]
@Ashutoshsahoo164 can you verify if issue is resolved?

**Comment by Raghu-addepalli** [comment]
![image](https://user-images.githubusercontent.com/91586743/220278546-fd60f287-8586-485e-999c-ee4442eed5a5.png)
verified the issue in below https://microsoft.github.io/30daysof/ environment the controls causing the issue are not available in environment hence closing the bug and added attachment.
Githubtags: #Closed;
