### ISSUE TITLE
Site updtes

### ISSUE THREAD

**Issue by leestott** [microsoft/30daysof#2]
@nitya 
Standardise
Top Level - 30 days of
Sub Levels - Template of course with content items (allowing you to scaffold 30 days of)
Author Guide
Analytics Guide

Structure 
Top Level Menu Student Hub - Link to Learn student hub http://aka.ms/learnstudent
Top Level Menu Curricula - Dedicated page with Images http://aka.ms/curricula
Community discussion based on Github discussions

**Comment by nitya** [comment]
v1 site refresh completed
 - landing page changes done
 - curricula pages templated (with existing curricula added)
 - discussion forum created and linked
 - roadmaps and playbook section added (content updates in progress)
