### ISSUE TITLE
[Website Platform] Add compliance banners 

### ISSUE THREAD

**Issue by nitya** [microsoft/30daysof#72]

**Comment by theoyinbooke** [comment]
Hi @nitya will this banner address the cookies issue as well?

**Comment by nitya** [comment]
@theoyinbooke - it was actually specifically for that issue. So, yes.

**Comment by nitya** [comment]
Updated Clarity to remove cookies at source.
Will experiment with banner addition for reference as well.

**Comment by nitya** [comment]
Closing this for now - we removed cookies and have no privacy information maintained so the cookie banner requirement is not relevant now. We can re-open if we context changes.
